PORTNAME=	lang
PORTVERSION=	25.1
CATEGORIES=	sysutils
PKGNAMEPREFIX=	${GH_ACCOUNT}-

MAINTAINER=	franco@yetisense.org
COMMENT=	YETIsense translations
WWW=		https://github.com/Christopher-YeTI/lang

LICENSE=	BSD2CLAUSE

USES=		gettext-tools

NO_ARCH=	yes
NO_BUILD=	yes

USE_GITHUB=	yes
GH_ACCOUNT=	${CATEGORIES:[1]}

.include <bsd.port.mk>
