PORTNAME=	dhcrelay
DISTVERSION=	1.0
CATEGORIES=	net

MAINTAINER=	franco@yetisense.org
COMMENT=	OpenBSD dhcrelay daemons
WWW=		https://github.com/Christopher-YeTI/dhcrelay

LICENSE=	BSD3CLAUSE

CONFLICTS_INSTALL=	isc-dhcp44-relay

USE_GITHUB=	yes
GH_ACCOUNT=	${CATEGORIES:[1]}

.include <bsd.port.mk>
